# Generated by Django 5.1.2 on 2024-10-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_trabajador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='nombre_contacto',
            new_name='nombre',
        ),
    ]
